# Generated by Django 5.1.2 on 2024-11-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_author_alter_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
