# Generated by Django 5.1.2 on 2024-11-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_remove_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
